### PR TITLE
Modified free_list.allocateEligible so that it will allocate the value of toAllocate

### PR DESCRIPTION
**Pull request by andrewwvc**
It seemed apparant that allocateEligible should request 'max' bytes from the parent, otherwise a bigger subsequent allocation that takes the returned memory from the root may slice an array too large. I tested this by creating a class that was 24 bytes, allocating and then deallocating a number of them (4 at a time) on a free_list (with minSize 24, maxSize 108) on top of a mallocator, then switching to allocating a class that used the max, which caused a crash.

### CODE REVIEW

**Comment by andralex** [comment]
Sorry, I missed this for a while. Could you please rebase and clean up the unrelated commits? Thanks!

**Comment by andralex** [comment]
In the meantime the branch has been merged in the mainline, any chance you could retarget the PR as a PR for phobos?

**Comment by andrewwvc** [comment]
I should be able to make the change, but in that case I want you to make it clear what you intend the code to do in the case that max == unbounded and how hasTolerance is supposed to factor into this.

Clearly, when min and max are finite, but differ, then an allocation request withing those bounds should allocate a buffer with max size, so that if the memory it put onto the free_list it can then be popped off and used interchangably by an allocation that requires a larger size, but is also in the allocator's bounds. Outside of those bounds, the allocation to forwarded to the parent allocator. However, the alocation mearly uses 'bytes', in the case that hasTolerance is true, yet I am not certain how you intend allocation to behave when the bounds are 'unchecked' and reliant on an owning allocator, as per the documentaion.

**Comment by andralex** [comment]
Totally missed this. Apologies! Could you please redo this PR against phobos?

**Pull request closed without merging**
