### PR TITLE
add approxMaxNodes parameter

### PR DESCRIPTION
**Pull request by 9il**
special values are `unbounded` and `chooseAtRuntime`. Added corresponding property `approxMaxLength`. @andralex

### CODE REVIEW

**Comment by andralex** [comment]
Sorry, missed this and now it's messed up. Could you please rebase? Thanks!

**Comment by 9il** [comment]
Rebased

**Comment by andralex** [comment]
Thanks! In the meantime the branch has been merged in the mainline. What's an effective way to merge your work there? BTW I think the addition is worthwhile.

**Comment by 9il** [comment]
Great news! I am going to create Phobos PR :)

**Comment by andralex** [comment]
awesome, thanks!

**Comment by 9il** [comment]
Created - https://github.com/D-Programming-Language/phobos/pull/3684

**Pull request closed without merging**
